apiVersion: v1
kind: Pod
metadata:
  name: postgress-app-pod
  labels:
    name: postgress-pod
    app: demo-voting-app2
spec:
  containers:
  - name: postgress
    image: postgress:9.4
    ports:
    - containerPort: 5432
