apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
   name: redis-Service
   app: demo-voting-app2
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app2
